name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: web-server-userland/fastify-workflows/.github/workflows/plugin-ci-pnpm.yml@v1
    with:
      coveralls: true
